services:
  - type: web
    name: vulnerability-scanner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --log-level=debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
